language: go
go:
  - 1.15.x
os:
  - linux

after_success:
  -

deploy:
- provider: releases
  token: $GITHUB_TOKEN
  name: gfs-pvinfo $TRAVIS_TAG
  file: gfs-pvinfo-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: cccfs/gfs-pvinfo
    tags: true